### ISSUE TITLE
command not found: tutor_app.py 

### ISSUE THREAD

**Issue by adelnr** [tushar2704/LingoChat#1]
Hi am trying to run LingoChat but showing to me in terminal :
LingoChat-main % tutor_app.py
zsh: command not found: tutor_app.py 

how i can fix it
thank you

**Comment by tushar2704** [comment]
Hi please find updated file name, ```LingoChat.py```

**Comment by adelnr** [comment]
Hi Tushar yea i found it and i made sure its updated but still have having same issue and when I try to run LingoChat.py give me this :
 Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run LingoChat.py [ARGUMENTS]
Traceback (most recent call last):
  File "LingoChat.py", line 21, in <module>
    st.stop()
  File "/.......LingoChat-main/venv/lib/python3.7/site-packages/streamlit/commands/execution_control.py", line 43, in stop
    raise StopException()
streamlit.runtime.scriptrunner.script_runner.StopException

**Comment by adelnr** [comment]
thank you for your reply
